### ISSUE TITLE
citrix_adc_servicegroup servicemembers not usable

### ISSUE THREAD

**Issue by RayquazID** [citrix/citrix-adc-ansible-modules#101]
Hi Giorgos,

i've got an issue while trying to add some servicemembers.
I've tried to use the example to see if the issue still occures with the example.

-------------------------------------------------
TASK [Setup http service with ip members] ****************************************************
fatal: [xx.xx.xx.xx -> localhost]: FAILED! => {"changed": false, "msg": "argument servicemembers is of type <class 'list'> and we were unable to convert to dict: <class 'list'> cannot be converted to a dict"}
-------------------------------------------------
the following playbook was used:
# The LB Monitors monitor-1 and monitor-2 must already exist
# Service members defined by C(ip) must not redefine an existing server's ip address.
# Service members defined by C(servername) must already exist.

  gather_facts: no
  tasks:
  - name: Setup http service with ip members
    delegate_to: localhost
    citrix_adc_servicegroup:
      nsip: 10.139.220.132
      nitro_user: nsroot
      nitro_pass: xxxxxxxxxxxxxxxxxxxx

      state: present

      servicegroupname: service-group-1
      servicetype: HTTP
      servicemembers:
      - ip: 10.78.78.78
        port: 80
        weight: 50
      - ip: 10.79.79.79
        port: 80
        weight: 40
-------------------------------------------------
ansible --version
ansible 2.9.1
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.5/site-packages/ansible
  executable location = /home/xxx/.local/bin/ansible
  python version = 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
-------------------------------------------------
if you need further debug output let me know!

**Comment by RayquazID** [comment]
okay i found the error

the docs inside of the module are different from the docs in /docs/modules

the missing line was:
servicemembers:
        mode: exact   <----- THIS
        attributes:        <----- THIS
          - ip: 10.78.78.78
            port: 80
            weight: 50
          - ip: 10.79.79.79
            port: 80
            weight: 40

maybe you could change that in the docs

**Comment by giorgos-nikolopoulos** [comment]
I am currently working on bringing the [readthedocs](https://netscaler-ansible.readthedocs.io/en/latest/) site up to date with the source repository.

I will update this issue when the changes are merged into master.

**Comment by giorgos-nikolopoulos** [comment]
fixed with #102
