### ISSUE TITLE
Non-adressable vservers?

### ISSUE THREAD

**Issue by magbra71** [citrix/citrix-adc-ansible-modules#104]
Hello,

Beeing at bit new to Ansible I'm wondering if there is a way to us the "non adressable" feature through Ansibel modules for in the netscaler_lb_vserver module? 
BR

**Comment by efenex** [comment]
Since I had the same question today and managed to solve it: specify the address as "0.0.0.0" and the port as "0" and you will get a non-addressable vserver.
