### ISSUE TITLE
Troubleshooting citrix_adc_ssl_certkey.py issues

### ISSUE THREAD

**Issue by brilong** [citrix/citrix-adc-ansible-modules#105]
I'm calling citrix_adc_ssl_certkey and in some cases I get the following error:
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/tmp/ansible_citrix_adc_ssl_certkey_payload_ogPXim/__main__.py", line 374, in <module>
  File "/tmp/ansible_citrix_adc_ssl_certkey_payload_ogPXim/__main__.py", line 240, in main
KeyError: 'mas_proxy_call'
fatal: [myhostname -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_citrix_adc_ssl_certkey_payload_ogPXim/__main__.py\", line 374, in <module>\n  File \"/tmp/ansible_citrix_adc_ssl_certkey_payload_ogPXim/__main__.py\", line 240, in main\nKeyError: 'mas_proxy_call'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

I am not calling the module with max_proxy_call parameter, but I'm struggling to understand why the module errors out this way.  How can I easily troubleshoot why this module is failing?

**Comment by brilong** [comment]
To give more context, here's a call to citrix_adc_ssl_certkey with state: absent and mas_proxy_call: false:

Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_ssl_certkey.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: foo
<localhost> EXEC /bin/sh -c 'no_proxy=10.1.2.3 /usr/bin/python2 && sleep 0'
fatal: [myhostname -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "certkey": "myvipname.foo.com", 
            "mas_proxy_call": false, 
            "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "nitro_protocol": "https", 
            "nitro_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "nsip": "10.1.2.3", 
            "save_config": false, 
            "state": "absent", 
            "validate_certs": false
        }
    }, 
    "msg": "Unsupported parameters for (citrix_adc_ssl_certkey) module: mas_proxy_call Supported parameters include: cert, certkey, expirymonitor, inform, key, nitro_pass, nitro_protocol, nitro_timeout, nitro_user, notificationperiod, nsip, passplain, password, save_config, state, validate_certs"

If I remove mas_proxy_call: false, I get the following:

Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_ssl_certkey.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: foo
<localhost> EXEC /bin/sh -c 'no_proxy=10.1.2.3 /usr/bin/python2 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/tmp/ansible_citrix_adc_ssl_certkey_payload_EhGIdh/__main__.py", line 374, in <module>
  File "/tmp/ansible_citrix_adc_ssl_certkey_payload_EhGIdh/__main__.py", line 240, in main
KeyError: 'mas_proxy_call'
fatal: [myhostname -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_citrix_adc_ssl_certkey_payload_EhGIdh/__main__.py\", line 374, in <module>\n  File \"/tmp/ansible_citrix_adc_ssl_certkey_payload_EhGIdh/__main__.py\", line 240, in main\nKeyError: 'mas_proxy_call'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

I have resorted to leaving mas_proxy_call: false and adding failed_when: false to the task, but that is obviously just masking the problem.  Thank you for any ideas on how to fix this issue.

**Comment by brilong** [comment]
I have tried moving from using citrix_adc_ssl_certkey to citrix_adc_nitro_request calling sslcertkey, but I cannot determine why I'm getting a different error:

Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_nitro_request.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: foo
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
fatal: [testhost -> localhost]: FAILED! => {
    "changed": false, 
    "headers": {
        "Content-Type": "application/json", 
        "X-NITRO-PASS": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
        "X-NITRO-USER": "foobar"
    }, 
    "http_response_body": "{ \"errorcode\": 1095, \"message\": \"Required argument missing [certkeyName]\", \"severity\": \"ERROR\" }", 
    "http_response_data": {
        "cache-control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0", 
        "connection": "close", 
        "content-length": "96", 
        "content-type": "application/json; charset=utf-8", 
        "date": "Mon, 13 Jan 2020 20:13:59 GMT", 
        "expires": "Thu, 19 Nov 1981 08:52:00 GMT", 
        "msg": "HTTP Error 400: Bad Request", 
        "pragma": "no-cache", 
        "server": "Apache", 
        "status": 400, 
        "url": "https://10.1.1.6/nitro/v1/config/sslcertkey"
    }, 
    "invocation": {
        "module_args": {
            "action": null, 
            "args": {
                "certkey": "testhost.foo.com", 
                "certkeyName": "testhost.foo.com"
            }, 
            "attributes": {
                "cert": "testhost.foo.com.cer", 
                "expirymonitor": "enabled", 
                "inform": "PEM", 
                "key": "testhost.foo.com.key", 
                "notificationperiod": 30
            }, 
            "expected_nitro_errorcode": [
                0
            ], 
            "filter": null, 
            "instance_id": null, 
            "instance_ip": null, 
            "instance_name": null, 
            "name": "testhost.foo.com", 
            "nitro_auth_token": null, 
            "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "nitro_protocol": "https", 
            "nitro_user": "foobar", 
            "nsip": "10.1.1.6", 
            "operation": "add", 
            "resource": "sslcertkey", 
            "timeout": 45, 
            "validate_certs": false
        }
    }, 
    "msg": "NITRO Failure", 
    "nitro_errorcode": 1095, 
    "nitro_message": "Required argument missing [certkeyName]", 
    "nitro_severity": "ERROR"
}

How can I get citrix_adc_ssl_certkey working properly?

**Comment by giorgos-nikolopoulos** [comment]
Could you include the source playbook and the output of the run with the `-vvv` parameter set?


I usually do this to get all output to the log.txt file
```bash
ansible-playbook myplaybook.yaml -vvv |& tee log.txt
```

Also could your include the Citrix ADC version your are using?

Meanwhile here is a sample invocation of citrix_adc_ssl_certkey taken from the integration tests.

This runs correctly as part of the integration test suite.

```yaml

- name: Setup
  delegate_to: localhost
  register: result
  citrix_adc_ssl_certkey:
    nitro_user: "{{nitro_user}}"
    nitro_pass: "{{nitro_pass}}"
    nsip: "{{nsip}}"

    state: present

    certkey: certirificate_1
    cert: /var/tmp/certificate1.crt
    key: /var/tmp/key1.pem
    expirymonitor: enabled
    notificationperiod: 30
    inform: PEM
    password: False
    passplain: somesecret
```

**Comment by brilong** [comment]
If I have a support agreement with Citrix for my Netscaler SDX appliances, is there a more official support mechanism I can use to continue this conversation so my detailed playbook and VPX version information is not public knowledge?  Thank you.

**Comment by brilong** [comment]
We're running the latest VPX 11.1 code since 12.1 has not yet been qualified as a SSP release.  Our SSL keys are not password-protected, so I am not using the password nor passplain arguments.  My main question is around the mas_proxy_call KeyError.  If I am not using a MAS in my environment, why is the module bombing out?  Are their API bugs in the VPX 11.1 code that are only fixed in 12.1 or higher?

**Comment by giorgos-nikolopoulos** [comment]
So I ran the integration tests against VPX 11.1 build 63.9 and they were successful.

The error you are reporting is a bit strange.

One cause could be if your installation is not correct.
Perhaps you have some older module version with the module utilities being imported from another mismatched version.

That's why I would like to see the execution log with the `-vvv` flag so I can check the paths used. 

If you can, run a fresh installation of ansible and the ADC modules taken from this repository and installed with the `install.py` script to see if the error is duplicated.

Other than that I would need  the source of the playbook and the detailed output of the run to troubleshoot this issue further.

As for the support channel you are on the right place.

You can send me the playbooks and output at my citrix email address and we can continue this conversation there if there are confidentiality issues.

**Comment by brilong** [comment]
I can tell you that running the equivalent CLI command works as needed.  I currently have commented-out code that is broken (using the API) and I have an expect+ssh script that works perfectly.  See below:

#  - name: Certs | enable the cert
#    delegate_to: localhost
#    citrix_adc_ssl_certkey:
#      nsip: "{{ netscaler_host_ip }}"
#      nitro_user: "{{ netscaler_nitro_user  }}"
#      nitro_pass: "{{ netscaler_nitro_password }}"
#      nitro_protocol: "{{ netscaler_nitro_protocol }}"
#      nitro_timeout: "{{ netscaler_timeout|default(omit) }}"
#      validate_certs: "{{ netscaler_validate_certs }}"
#      status: present
#      save_config: "{{ netscaler_save_config }}"
#      certkey: "{{ netscaler_virtual_endpoint }}.{{ domain }}"
#      cert: "{{ netscaler_virtual_endpoint }}.{{ domain }}.{{ certificates_cert_extension }}"
#      key: "{{ netscaler_virtual_endpoint }}.{{ domain }}.{{ certificates_key_extension }}"
#      linkcertkey: "{{ netscaler_linkcertkey | default(omit)}}"
#      inform: "PEM"
#      expirymonitor: enabled
#      notificationperiod: 30
#    register: sslcertkey_add_result

  - name: Certs | enable the SSL cert using expect+ssh
    delegate_to: localhost
    shell: |
      set timeout 30
      spawn ssh -o StrictHostKeyChecking=no {{netscaler_nitro_user}}@{{netscaler_host_ip}}
      expect "Password:"
      send "{{ netscaler_nitro_password }}\n"
      expect "> "
      send "add ssl certKey {{ netscaler_virtual_endpoint }}.{{ domain }} -cert {{ netscaler_virtual_endpoint }}.{{ domain }}.{{ certificates_cert_extension }} -key {{ netscaler_virtual_endpoint }}.{{ domain }}.{{ certificates_key_extension }} -bundle no\n"
      expect "> "
      send "exit\n"
      expect "Save changes now"
      send "n\n"
      exit 0
    args:
      executable: /usr/bin/expect
    no_log: True
    register: sslcertkey_add_result
