### ISSUE TITLE
Latest code install: "Could not find imported module support code for citrix_adc_server.  Looked for either get_immutables_intersection.py or citrix_adc.py"

### ISSUE THREAD

**Issue by brilong** [citrix/citrix-adc-ansible-modules#109]
I downloaded and installed the latest code today.  When I call the citrix_adc_server module, I get the following error:
Could not find imported module support code for citrix_adc_server.  Looked for either get_immutables_intersection.py or citrix_adc.py

I have Ansible 2.8.7 RPM installed on a RHEL 7 host.

The installation log:
# pip install deps/nitro-python-1.0_kamet.tar.gz
Processing ./deps/nitro-python-1.0_kamet.tar.gz
  Requirement already satisfied (use --upgrade to upgrade): nitro-python==1.0 from file:///root/citrix-adc-ansible-modules-master/deps/nitro-python-1.0_kamet.tar.gz in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /usr/lib/python2.7/site-packages (from nitro-python==1.0)
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

# pip install --upgrade deps/nitro-python-1.0_kamet.tar.gz
Processing ./deps/nitro-python-1.0_kamet.tar.gz
Collecting requests>=2.3.0 (from nitro-python==1.0)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.3.0->nitro-python==1.0)
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 3.2MB/s
Collecting certifi>=2017.4.17 (from requests>=2.3.0->nitro-python==1.0)
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 3.1MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.3.0->nitro-python==1.0)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 5.6MB/s
Requirement already up-to-date: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->nitro-python==1.0)
Installing collected packages: urllib3, certifi, chardet, requests, nitro-python
  Found existing installation: urllib3 1.10.2
    Uninstalling urllib3-1.10.2:
      Successfully uninstalled urllib3-1.10.2
  Found existing installation: certifi 2019.9.11
    Uninstalling certifi-2019.9.11:
      Successfully uninstalled certifi-2019.9.11
  Found existing installation: chardet 2.2.1
    Uninstalling chardet-2.2.1:
      Successfully uninstalled chardet-2.2.1
  Found existing installation: requests 2.6.0
    DEPRECATION: Uninstalling a distutils installed project (requests) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling requests-2.6.0:
      Successfully uninstalled requests-2.6.0
  Found existing installation: nitro-python 1.0
    Uninstalling nitro-python-1.0:
      Successfully uninstalled nitro-python-1.0
  Running setup.py install for nitro-python ... done
Successfully installed certifi-2019.11.28 chardet-3.0.4 nitro-python-1.0 requests-2.22.0 urllib3-1.25.8
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

# python install.py
Ansible path is /usr/lib/python2.7/site-packages/ansible
Ansible extras path is /usr/lib/python2.7/site-packages/ansible/modules/network
Copying documentation fragments to /usr/lib/python2.7/site-packages/ansible/plugins/doc_fragments
Copying netscaler.py to /usr/lib/python2.7/site-packages/ansible/module_utils/network/netscaler
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/__init__.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_confidfield.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_fieldtype.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_global_bindings.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_htmlerrorpage.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_jsoncontenttype.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_learningsettings.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_policy.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_policylabel.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_profile.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_settings.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_signatures.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_wsdl.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_xmlcontenttype.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_xmlerrorpage.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_appfw_xmlschema.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_cs_action.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_cs_policy.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_cs_vserver.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_gslb_service.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_gslb_site.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_gslb_vserver.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_lb_monitor.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_lb_vserver.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_nitro_request.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_nitro_resource.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_save_config.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_server.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_service.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_servicegroup.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adc_ssl_certkey.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_application.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_dns_domain_entry.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_login.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_mpsgroup.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_mpsuser.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_ns_facts.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_poll_instances.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_rba_policy.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_rba_role.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_stylebook.py
Overwriting /usr/lib/python2.7/site-packages/ansible/modules/network/netscaler/citrix_adm_tenant_facts.py
Warning. Could not install unit tests. You will not be able to run the unit tests for the modules.
This does not affect normal module functionality.
Installing Citrix ADC connection plugin

What am I missing?  Thanks.

**Comment by brilong** [comment]
I downloaded the v1.8 ZIP file and installed using the same method and everything works fine.

**Comment by giorgos-nikolopoulos** [comment]
This is an error in the install script.

I will be fixing this soon

**Comment by giorgos-nikolopoulos** [comment]
Fixed with 86a1517
