### ISSUE TITLE
urlopen error - request module

### ISSUE THREAD

**Issue by DevGumbo** [citrix/citrix-adc-ansible-modules#118]
fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false,
    "headers": {
        "Content-Type": "application/json",
        "X-NITRO-PASS": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "X-NITRO-USER": "$USER"
    },
    "http_response_body": "",
    "http_response_data": {
        "msg": "Request failed: <urlopen error timed out>",
        "status": -1,
        "url": "https://1.1.1.1/nitro/v1/config/lbvserver?filter=ipv46:5.5.5.5"
    },
    "invocation": {
        "module_args": {
            "action": null,
            "args": null,
            "attributes": null,
            "expected_nitro_errorcode": [
                0
            ],
            "filter": {
                "ipv46": "5.5.5.5"
            },
            "instance_id": null,
            "instance_ip": null,
            "instance_name": null,
            "name": null,
            "nitro_auth_token": null,
            "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nitro_protocol": "https",
            "nitro_user": "$USER",
            "nsip": "10.10.10.10",
            "operation": "get_filtered",
            "resource": "lbvserver",
            "timeout": 45,
            "validate_certs": false
        }
    },
    "msg": "NITRO Failure",
    "nitro_errorcode": -1,
    "nitro_message": "Request failed: <urlopen error timed out>",
    "nitro_severity": "ERROR"

So i obscured the connection details in terms of the user and ip address but they were valid user accounts and login nsip ip as i am able to use the pythong SDK to run the commands as a standalone solution but keep getting the above error when trying to run the ansible module.

I tried 2 different ways 
one using darwin to find the host python and the other was by setting the python interpreter in the vars to my venv py3

Here is teh config playbook

vars:
    ansible_python_interpreter: ~/Home/Environments/Ansible/bin/python3
    resource: lbvserver
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6

  tasks:
    - name: Get filtered
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        nitro_protocol: 'https'
        validate_certs: "{{validate_certs}}"

        operation: get_filtered

        resource: "{{ resource }}"
        filter:
          ipv46: 5.5.5.5

note the  actual ip in the vars is not actually an ip address in the config of the vpx however i dont suspect that to be an issue yet as it doesnt seem to even be logging in.
Same goes for the name of the server not actually being a name of a lbvserver in my config on the box just something i was leaving to see how it would deal with an asset that is not present on the config .

**Comment by giorgos-nikolopoulos** [comment]
I cannot reproduce the error with the latest stable Ansible version 2.10.

`citrix_adc_nitro_request` uses the `fetch_url` method provided by Ansible core.

Please update to the latest Ansible stable version and rerun the playbook.
