### ISSUE TITLE
Support for  --diff in modules

### ISSUE THREAD

**Issue by ppieprzycki** [citrix/citrix-adc-ansible-modules#127]
Hello All, 
I'm struggling with providing information about what will be exactly changed after executing playbook. 
Some of the information is visible in debug but it's not always accurate and requires to check code. 

Would be great to have supported --diff options in modules (also with --check) at least in core modules (servers, server, service group etc..) 
Is there any module that can be used as a valid example of how to handle it? 

Would be great to hear also how are you checking your ranges before applying to production. 

Regards

**Comment by giorgos-nikolopoulos** [comment]
We will take this into consideration for future planning of development efforts.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #179

Diff mode was added to the following modules
citrix_adc_cs_vserver
citrix_adc_lb_vserver
citrix_adc_service
citrix_adc_servicegroup
citrix_adc_nitro_resource
