### ISSUE TITLE
Modules as Ansible Collection 

### ISSUE THREAD

**Issue by ppieprzycki** [citrix/citrix-adc-ansible-modules#128]
Hi,
is there a plan for creating a collection  for ansible based on this repo?  Or maybe there is already one?

**Comment by abenokraitis** [comment]
Looks like the existing content that was in Ansible 2.9 has been auto-migrated to `community.network` collection at https://galaxy.ansible.com/community/network . It may be best to move these out to a citrix namespace/collection if @giorgos-nikolopoulos thinks that may be easier to maintain/control.

**Comment by giorgos-nikolopoulos** [comment]
Collections have become available with #141 .
Currently only available from the github repository.
We are working on putting them on Ansible Galaxy

**Comment by matt6697** [comment]
A docker image containing Ansible 2.9.2 as well as the `citrix.adc` & `citrix.adm` collections has been publishedon docker hub to ease usage of those collections in a production network. 

@giorgos-nikolopoulos : As community PR are not accepted by Citrix, Dockerfile and CI pipeline (including dockerhub upload automation) provided on https://github.com/virtualdesktopdevops/citrix-adc-ansible-modules-docker if you want to include this feature to the official repository.
