### ISSUE TITLE
Clarity. This is the Standard Ansible Modules Upstream Git?

### ISSUE THREAD

**Issue by JustAShoeMaker** [citrix/citrix-adc-ansible-modules#132]
This is the feeder Git for the standard ansible modules listed in their module index? (and I see, compared to 2.9, there are a boatload more on the way).

the naming overlap (before the adc change) was highly correlated. But clearly became richer...
.
Thanks.. I mean ευχαριστώ συμπατριώτη ;)

**Comment by giorgos-nikolopoulos** [comment]
Yes this is where the development happens for citrix adc modules.
We will be moving all modules and related content to Ansible Galaxy.

Right now  to get the latest modules, install Ansible and run the install.py script.

**Comment by giorgos-nikolopoulos** [comment]
We have moved to ansible collections for the distribution of modules.

Use of ansible 2.9 or later is required for this.
