### ISSUE TITLE
Default LB Vserver "IndexError" in citrix_adc_cs_vserver module

### ISSUE THREAD

**Issue by JoshHester** [citrix/citrix-adc-ansible-modules#136]
It appears that the citrix_adc_cs_vserver module reports a non-0 response code when using it to create or update a content switching virtual server object that has no default load balance virtual server defined.

Here's the exact traceback response:

> The full traceback is:
> Traceback (most recent call last):
>   File "/home/joshes/.ansible/tmp/ansible-tmp-1596485548.56-1814-144237611523981/AnsiballZ_citrix_adc_cs_vserver.py", line 102, in <module>
>     _ansiballz_main()
>   File "/home/joshes/.ansible/tmp/ansible-tmp-1596485548.56-1814-144237611523981/AnsiballZ_citrix_adc_cs_vserver.py", line 94, in _ansiballz_main
>     invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
>   File "/home/joshes/.ansible/tmp/ansible-tmp-1596485548.56-1814-144237611523981/AnsiballZ_citrix_adc_cs_vserver.py", line 40, in invoke_module
>     runpy.run_module(mod_name='ansible.modules.network.netscaler.citrix_adc_cs_vserver', init_globals=None, 
> run_name='__main__', alter_sys=True)
>   File "/usr/lib/python2.7/runpy.py", line 188, in run_module
>     fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
>     mod_name, mod_fname, mod_loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/tmp/ansible_citrix_adc_cs_vserver_payload_mVXoq0/ansible_citrix_adc_cs_vserver_payload.zip/ansible/modules/network/netscaler/citrix_adc_cs_vserver.py", line 1491, in <module>
>   File "/tmp/ansible_citrix_adc_cs_vserver_payload_mVXoq0/ansible_citrix_adc_cs_vserver_payload.zip/ansible/modules/network/netscaler/citrix_adc_cs_vserver.py", line 1438, in main
>   File "/tmp/ansible_citrix_adc_cs_vserver_payload_mVXoq0/ansible_citrix_adc_cs_vserver_payload.zip/ansible/modules/network/netscaler/citrix_adc_cs_vserver.py", line 723, in default_lb_vserver_identical
>   File "/tmp/ansible_citrix_adc_cs_vserver_payload_mVXoq0/ansible_citrix_adc_cs_vserver_payload.zip/ansible/modules/network/netscaler/citrix_adc_cs_vserver.py", line 708, in get_default_lb_vserver
> IndexError: list index out of range

The module seems to actually perform most of the actions requested.  If creating a new object, it creates it with all settings specified in the play _except_ the default LB Vserver; likewise, if updating an existing object, I can see new settings getting configured that weren't previously.  However, in all cases where the target CS vserver object has no Default LB Vserver specified at play runtime, the return in Ansible is the fatal error above.

I have captured my troubleshooting scenarios and their results:
- Run play with no 'lbvserver' value specified where no CS vserver exists presently: creates CS vserver with no default LB vserver, throws error
- Run play with no 'lbvserver' value specified where a CS vserver exists with no default LB Vserver specified: updates CS vserver as expected, throws error
- Run play with 'lbvserver' value specified where no CS vserver exists presently: creates CS vserver with no default LB vserver, throws error
- Run play with no 'lbvserver' value specified where a CS vserver exists with a default LB Vserver specified: removes default LBVserver, no error
- Run play with 'lbvserver' value specified where a CS vserver exists with a default LB Vserver specified that is the same as in the play: first run shows 'changed,' subsequent runs show 'ok,' no error
- Run play with 'lbvserver' value specified where a CS vserver exists with a default LB Vserver specified that is different than in the play: shows 'changed,' updates default LB Vserver, no error
- Run play with no 'lbvserver' value specified where a CS vserver exists with a default LB Vserver specified: removes default LB Vserver, no error

Here's my Ansible version info:

> ansible 2.9.10
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = [u'/home/joshes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/dist-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

Target Citrix ADC's are running version 12 build 55.18.

**Comment by Belabacsi** [comment]
I have experienced the same. The module drops this error message when "lbvserver" attribute is empty in the NS-VPX configuration. In case "lbvserver" attribute is configured, script works as expected: it can update and change "lbvserver" attribute value, if "lbvserver" attribute exists but configured for a different value.

`ansible 2.10.1`
`python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]`

**Comment by giorgos-nikolopoulos** [comment]
I cannot reproduce the error.

We recently rewrote `citrix_adc_cs_vserver` with #163 .

Can you verify that the bug still exists?

**Comment by giorgos-nikolopoulos** [comment]
Cannot verify the bug.

Please open a new issue if you continue to see the same behavior.
