### ISSUE TITLE
Rename collections (in galaxy.yml)

### ISSUE THREAD

**Issue by thedoubl3j** [citrix/citrix-adc-ansible-modules#142]
This is mainly look and feel but I would recommend changing the names of the collections just to the product name. 

Users will know they are downloading from citrix due to the namespace argument being passed

Rather than something like `citrix.citrixadc_modules` something like `citrix.adc` would be simpler and follow the pattern `$company.$product`. 

I can open a PR for this if desired.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #145

collections renamed to `adc` and `adm` respectively
