### ISSUE TITLE
Create tests/ dirs in each collection

### ISSUE THREAD

**Issue by thedoubl3j** [citrix/citrix-adc-ansible-modules#144]
This is mainly so that you can add ignore [files](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html) to ignore tests as needed. (for example, you all do not support python 2.6 so you can line items to completely ignore those tests)

Creating this dir, you can put the specific unit/integration tests you write here for each collection and you can leverage ansible-test to run those locally/in CI if you wish.

**Comment by giorgos-nikolopoulos** [comment]
Currently there are no sanity tests failing.
Running `ansible-test sanity --docker` on both collections returns with no errors.

If future tests start failing we will add ignores.

**Comment by thedoubl3j** [comment]
sounds good @giorgos-nikolopoulos also, ++ for running the tests with the --docker command
