### ISSUE TITLE
Not installable using ansible-galaxy

### ISSUE THREAD

**Issue by wwerther** [citrix/citrix-adc-ansible-modules#146]
When trying to install with ansible-galaxy I get the error message that this collection does not exist. Also if you search on https://galaxy.ansible.com/search there is no chance to find this collection either with citrix, nor with netscaler or adc

-> ansible-galaxy collection install citrix.adc
-> Process install dependency map
ERROR! Failed to find collection citrix.adc:*

**Comment by giorgos-nikolopoulos** [comment]
The modules are not yet uploaded to Ansible Galaxy.

You can install them with the `ansible-galaxy` command line tool from this repository.

See this [section](https://github.com/citrix/citrix-adc-ansible-modules#installation) of the README for details.
