### ISSUE TITLE
Changing default parameteres with object

### ISSUE THREAD

**Issue by mokaADC** [citrix/citrix-adc-ansible-modules#153]
Hi,
on a NS:
https://<nsip>/nitro/v1/config/sslparameter
You get a list of parameteres, how do i go about changing these default parameteres with "object"? It seems like "object" always wants a key, and in the default parameteres, there is no key.
Doing a citrix_adc_nitro_request works, but then i get a "changed=1" everytime i run my playbook.

**Comment by giorgos-nikolopoulos** [comment]
This would require a new workflow to be implemented in the `citrix_adc_nitro_resource` module.

We have not allocated time for this as of yet.

We will keep this in mind for any future planning.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #174.

A new workflow `parameter_object` was added that is appropriate for the `sslparameter` endpoint
