### ISSUE TITLE
citrix_adc_lb_vserver - redirurl parameter sets value for two different configuration values

### ISSUE THREAD

**Issue by LizK-TTS** [citrix/citrix-adc-ansible-modules#169]
On a load balancing virtual server I am trying to set, under basic settings, the 'redirect from port' and 'https redirect URL'. We use this to ensure port 80 redirects to 443.

In my Ansible task I am using the citrix_adc_lb_vserver module and using the **redirecfromport** and **redirurl** parameters.

The **redirectfromport** works as expected.

Using the **redirurl** will set the specified value in multiple places of the load balancing virtual server configuration. It gets set where I expected, basic settings for "HTTPS redirect URL" but it also gets set under protection settings for "Redirect URL". I believe the intention is this parameter does set the protection settings - redirect URL based on the documentation.

Can you please fix the current **redirurl** to ensure it only sets the protection - redirect URL setting and then create a new parameter to set the basic settings - HTTPS redirect URL?

**Comment by giorgos-nikolopoulos** [comment]
You can set the https redirect url with the `httpsredirecturl` option.
Other than that the NITRO API operates just as the cli does for the `redirurl` option.

Could you provide us with the cli commands and output that showcases your issue?

**Comment by LizK-TTS** [comment]
When trying to configure a scenario to provide more information I realized I was making an assumption that was incorrect. 

I was assuming that when "redirurl" parameter was set to https://10.0.0.25 the Ansible module was setting this value for both "redirurl" and "httpsredirecturl" but the behaviour I'm experiencing is happening because I am also setting a value for "redirectfromport". The "httpsredirecturl" value is being automatically populated with https://10.0.0.25 (the IP on the load balancing vs) when "redirectfromport" has a value.

Sorry for making this assumption, I'll try to be more thorough when reporting issues in the future. 

On a side note, httpsredirecturl and backupvserver parameters are missing from the citrix_adc_lb_vserver documentation.
