### ISSUE TITLE
Request for module parameter - citrix_adc_lb_vserver - 'backup virtual server' needed

### ISSUE THREAD

**Issue by LizK-TTS** [citrix/citrix-adc-ansible-modules#170]
For the citrix_adc_lb_vserver module... can you please add a parameter to be able to set the 'backup virtual server' value? This can be found under the Protection in the Netscaler UI and I cannot find a parameter in the citrix_adc_lb_vserver that can set this value via Ansible.

**Comment by vadharm** [comment]
Will review the issue and get back to you.

**Comment by giorgos-nikolopoulos** [comment]
The option to set the backup virtual server is `backupvserver`
