### ISSUE TITLE
citrix_adc_ssl_certkey - CA cert install from bundle pem file fails when intermediate CAs are already present

### ISSUE THREAD

**Issue by semora81** [citrix/citrix-adc-ansible-modules#185]
I have tried to import a CA bundle which is comprised of 3 certificates, a Root authority and 2 intermediate CAs. 

when trying to import the pem file as a bundle, the ADC Nitro api splits it into 3 files if Bundle: yes is set in the module parameters. The UI does this also by default when installing a CA cert bundle. 

Then if we set the state to absent on the CA cert, with same code, it is removed. 

This all works fine, however, only the root CA is removed, none of it's linked intermediates. 

This is where the issue occurs, once we re-run the install of the certificate, it fails with errors: 

```
    "loglines": [
        "ModuleExecutor.calculate_configured_ssl_certkey()", 
        "calculated configured ssl certkey {'certkey': 'cachain', 'bundle': 'YES', 'inform': 'PEM', 'cert': 'cachain.pem', 'notificationperiod': '30', 'expirymonitor': 'ENABLED', 'deletefromdevice': True}", 
        "ModuleExecutor.update_or_create()", 
        "ModuleExecutor.ssl_certkey_exists()", 
        "get result {'nitro_severity': u'ERROR', 'nitro_message': u'Certificate does not exist', 'nitro_errorcode': 1540, 'http_response_data': {'status': 599, 'content-length': '83', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'vary': 'Accept-Encoding', 'pragma': 'no-cache', 'date': 'Tue, 23 Mar 2021 03:07:48 GMT', 'server': 'Apache', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'url': 'https://xxxxxxx/nitro/v1/config/sslcertkey/cachain', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'connection': 'close', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'msg': 'HTTP Error 599: Netscaler specific error', 'x-frame-options': 'SAMEORIGIN', 'referrer-policy': 'no-referrer', 'content-type': 'application/json; charset=utf-8'}, 'data': {u'errorcode': 1540, u'message': u'Certificate does not exist', u'severity': u'ERROR'}}", 
        "ssl certkey does not exist. Will create.", 
        "ModuleExecutor.create_ssl_certkey()", 
        "post data: {'sslcertkey': {'certkey': 'cachain', 'bundle': 'YES', 'inform': 'PEM', 'cert': 'cachain.pem', 'notificationperiod': '30', 'expirymonitor': 'ENABLED'}}", 
        "result of post: {'nitro_severity': u'ERROR', 'nitro_message': u'Certificate file for intermediate certificate already exists. [/nsconfig/ssl/cachain.pem_ic1]', 'nitro_errorcode': 3660, 'http_response_data': {'status': 599, 'content-length': '153', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'url': 'https://xxxxxxxx/nitro/v1/config/sslcertkey', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'connection': 'close', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'date': 'Tue, 23 Mar 2021 03:07:48 GMT', 'x-frame-options': 'SAMEORIGIN', 'server': 'Apache', 'content-type': 'application/json; charset=utf-8', 'msg': 'HTTP Error 599: Netscaler specific error'}, 'data': {u'errorcode': 3660, u'message': u'Certificate file for intermediate certificate already exists. [/nsconfig/ssl/cachain.pem_ic1]', u'severity': u'ERROR'}}"
    ], 
    "msg": "nitro exception errorcode=3660, message=Certificate file for intermediate certificate already exists. [/nsconfig/ssl/cachain.pem_ic1], severity=ERROR"
```

The check if certificate exists is done only on the first certificate, the actual one being created, not on the bundle. 

when the bundle = true is set, each cert in the bundle should be checked for existence and only the individual ones who are missing should be created, then, the appropriate links should be done. 

i'm not sure I can propose a code fix on this one, not too sure where to start on this one given my limited experience on python

thanks

**Comment by giorgos-nikolopoulos** [comment]
The `bundle` option is only valid for the add operation.

So it is not possible to tell nitro to remove all the certificates in the bundle during the `delete` operation.

One solution would be to create tasks that are used only for deleting the extra certificates using a flag variable

For example you could use the `state` variable to execute the task only when `state == absent` like so:

```
  tasks:
    - name: Set ssl certificate key
      delegate_to: localhost
      when: 
        -  state == "absent"
      citrix.adc.citrix_adc_ssl_certkey:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: "{{ state }}"

        certkey: certificate_1
        cert: server.crt
        key: server.key
```

**Comment by giorgos-nikolopoulos** [comment]
Also another solution would be to split the bundled certificate into individual ones and then use them in the playbook.
Here is an example of how to do this https://stackoverflow.com/questions/23644473/how-can-i-split-a-ca-certificate-bundle-into-separate-files

**Comment by semora81** [comment]
I still believe that if the bundle: yes is present on state : absent , the module could loop on the linked certificates and cleanup if and only if those certes are not linked to another cert. a warning could be given if it could not be deleted.

Also, the code to add the bundle does not check for existence of the the different parts of the bundle. and then fails when adding existing certs from a bundle.

Indempotency would require the missing part to be recreated and linked but not the play to fail

Regards

Since the certificates end up being linked, the bundle option on delete

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : George Nikolopoulos ***@***.***>
Envoyé : Monday, March 29, 2021 7:26:52 AM
À : citrix/citrix-adc-ansible-modules ***@***.***>
Cc : Sebastien Morissette ***@***.***>; Author ***@***.***>
Objet : Re: [citrix/citrix-adc-ansible-modules] citrix_adc_ssl_certkey - CA cert install from bundle pem file fails when intermediate CAs are already present (#185)




    [E!] Warning! This email originated outside of our organization.
    [E!] Attention! Ce courriel provient de l'extérieur de notre organisation.



Also another solution would be to split the bundled certificate into individual ones and then use them in the playbook.
Here is an example of how to do this https://stackoverflow.com/questions/23644473/how-can-i-split-a-ca-certificate-bundle-into-separate-files<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F23644473%2Fhow-can-i-split-a-ca-certificate-bundle-into-separate-files&data=04%7C01%7Csebastien.morissette%40intact.net%7Cae44c618af694733cbb208d8f2a58d8a%7Cb880eecaf1fb4c91bff682e84350a6e6%7C0%7C0%7C637526140145103480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KBfw7QlK8dyuKdxHkOPYXV%2F%2BSs9vQ2sewrWPB%2FqekV8%3D&reserved=0>
