### ISSUE TITLE
citrix_adm_rba_policy -> can't create any policies with the adm module

### ISSUE THREAD

**Issue by semora81** [citrix/citrix-adc-ansible-modules#188]
I need to create an ADM 13 equivalent to a tenant using the rbac functions. 

i've been trying all day to understand the code and run a successfull playbook but i'm at a loss. 

I even tried running your sample directly and i get the same behavior, the rba policy is created, but is always empty. 

if I update via the gui, and run the playbook again, it will empy the policy. 

https://github.com/citrix/citrix-adc-ansible-modules/blob/master/samples/citrix_adm_rba_policy_full.yaml

there are plenty of warnings when running the sample 

[WARNING]: The value {'parent_name': 'rba_policy', 'access_type': True, 'id': 'fc1561b7-21dc-40d5-bee4-8b8cc6d39e07', 'parent_id': 'f7083e16-b110-4400-a536-40b3049e86a1', 'dependent_resources': '', 'operation_name': 'get',
'resource_type': 'ns_emon_poll_policy'} (type dict) in a string field was converted to u"{'parent_name': 'rba_policy', 'access_type': True, 'id': 'fc1561b7-21dc-40d5-bee4-8b8cc6d39e07', 'parent_id':
'f7083e16-b110-4400-a536-40b3049e86a1', 'dependent_resources': '', 'operation_name': 'get', 'resource_type': 'ns_emon_poll_policy'}" (type string). If this does not look like what you expect, quote the entire value to ensure
it does not change.

however, regardless if I simplify the usecase with less items for statements and ui list, the object always ends up being empty. 

are there tests run against the modules to ensure the are functional with different versions of ADM or ansible?

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #190

**Comment by vadharm** [comment]
Fixed with #190
