### ISSUE TITLE
lb vserver - can't bind a servicegroup

### ISSUE THREAD

**Issue by semora81** [citrix/citrix-adc-ansible-modules#191]
hi, i'm hitting an error when trying to create an lb vserver with a service group, it seems to expect a serviceName and weight, but this is a service group so it's in the dict... can you pinpoint what i'm doing wrong or if this is a bug?

my call:
- name: "deploy the lb vserver configuration -> {{ vserver.name }}"
  delegate_to: localhost
  collections:
    - citrix.adc
  citrix_adc_lb_vserver:
    nsip: "{{ nsip }}"
    nitro_user: "{{ uname }}"
    nitro_pass: "{{ upassword }}"
    state: "{{vserver.state|default('present')}}"
    name: "{{ vserver.name }}"
    servicetype: "{{ vserver.type }}"
    port: "{{vserver.port}}"
    lbmethod: "{{vserver.lbmethod|default('ROUNDROBIN')}}"
    servicegroupbindings: "{{vserver.servicegroupbindings|default(omit)}}"
    appfw_policybindings: "{{vserver.appfw_policybindings|default(omit)}}"

error stack:

The full traceback is:
  File "/tmp/ansible_citrix_adc_lb_vserver_payload_sgati_js/ansible_citrix_adc_lb_vserver_payload.zip/ansible_collections/citrix/adc/plugins/modules/citrix_adc_lb_vserver.py", line 2213, in main
  File "/tmp/ansible_citrix_adc_lb_vserver_payload_sgati_js/ansible_citrix_adc_lb_vserver_payload.zip/ansible_collections/citrix/adc/plugins/modules/citrix_adc_lb_vserver.py", line 1646, in update_or_create
  File "/tmp/ansible_citrix_adc_lb_vserver_payload_sgati_js/ansible_citrix_adc_lb_vserver_payload.zip/ansible_collections/citrix/adc/plugins/modules/citrix_adc_lb_vserver.py", line 2178, in sync_bindings
  File "/tmp/ansible_citrix_adc_lb_vserver_payload_sgati_js/ansible_citrix_adc_lb_vserver_payload.zip/ansible_collections/citrix/adc/plugins/modules/citrix_adc_lb_vserver.py", line 1953, in sync_servicegroup_bindings
  File "/tmp/ansible_citrix_adc_lb_vserver_payload_sgati_js/ansible_citrix_adc_lb_vserver_payload.zip/ansible_collections/citrix/adc/plugins/modules/citrix_adc_lb_vserver.py", line 1858, in add_servicegroup_binding
fatal: [s3management1 -> localhost]: FAILED! => {
    "changed": true,
    "diff_list": [
        "Attribute \"pq\" differs. Playbook parameter: (<class 'str'>) OFF. Retrieved NITRO object: (<class 'NoneType'>) None",
        "Attribute \"sc\" differs. Playbook parameter: (<class 'str'>) OFF. Retrieved NITRO object: (<class 'NoneType'>) None"
    ],
    "invocation": {
        "module_args": {
            "adfsproxyprofile": null,
            "appflowlog": null,
            "appfw_policybindings": null,
            "authentication": null,
            "authenticationhost": null,
            "authn401": null,
            "authnprofile": null,
            "authnvsname": null,
            "backuplbmethod": null,
            "backuppersistencetimeout": null,
            "backupvserver": null,
            "bypassaaaa": null,
            "cacheable": null,
            "clttimeout": 180,
            "comment": "Vserver created by ansible",
            "connfailover": null,
            "cookiename": null,
            "datalength": null,
            "dataoffset": null,
            "dbprofilename": null,
            "dbslb": null,
            "disabled": false,
            "disableprimaryondown": null,
            "dns64": null,
            "dnsprofilename": null,
            "downstateflush": "enabled",
            "hashlength": null,
            "healththreshold": null,
            "httpprofilename": null,
            "httpsredirecturl": null,
            "icmpvsrresponse": null,
            "insertvserveripport": null,
            "instance_ip": null,
            "ipmask": null,
            "ippattern": null,
            "ipset": null,
            "ipv46": "xxx.yyy.zzz.220",
            "l2conn": null,
            "lbmethod": "ROUNDROBIN",
            "lbprofilename": null,
            "listenpolicy": null,
            "listenpriority": null,
            "m": null,
            "macmoderetainvlan": null,
            "mas_proxy_call": false,
            "maxautoscalemembers": null,
            "minautoscalemembers": null,
            "mssqlserverversion": null,
            "mysqlcharacterset": null,
            "mysqlprotocolversion": null,
            "mysqlservercapabilities": null,
            "mysqlserverversion": null,
            "name": "DEV-STEVE-management_vsrv",
            "netmask": null,
            "netprofile": null,
            "newservicerequest": null,
            "newservicerequestincrementinterval": null,
            "newservicerequestunit": null,
            "nitro_auth_token": null,
            "nitro_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nitro_protocol": "https",
            "nitro_timeout": 310.0,
            "nitro_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nsip": "xxx.yyy.zzz.aaa",
            "oracleserverversion": null,
            "persistavpno": null,
            "persistencebackup": "NONE",
            "persistencetype": "NONE",
            "persistmask": null,
            "port": 443,
            "pq": false,
            "processlocal": null,
            "push": null,
            "pushlabel": null,
            "pushmulticlients": null,
            "pushvserver": null,
            "range": null,
            "recursionavailable": null,
            "redirectfromport": null,
            "redirectportrewrite": null,
            "redirurl": null,
            "redirurlflags": null,
            "resrule": null,
            "retainconnectionsoncluster": null,
            "rhistate": null,
            "rtspnat": null,
            "rule": null,
            "save_config": true,
            "sc": false,
            "servicebindings": null,
            "servicegroupbindings": [
                {
                    "servicegroupname": "DEV-STEVE-management_svcgrp",
                    "weight": "1"
                }
            ],
            "servicename": null,
            "servicetype": "SSL",
            "sessionless": null,
            "skippersistency": null,
            "sobackupaction": null,
            "somethod": null,
            "sopersistence": null,
            "sopersistencetimeout": null,
            "sothreshold": null,
            "ssl_certkey": null,
            "state": "present",
            "tcpprofilename": null,
            "td": null,
            "timeout": null,
            "tosid": null,
            "trofspersistence": null,
            "v6netmasklen": null,
            "v6persistmasklen": null,
            "validate_certs": false,
            "vipheader": null,
            "weight": null
        }
    },
    "loglines": [
        "ModuleExecutor.calculate_configured_lbvserver()",
        "calculated configured lbvserver {'name': 'DEV-STEVE-management_vsrv', 'servicetype': 'SSL', 'ipv46': 'xxx.yyy.zzz.220', 'port': 443, 'persistencetype': 'NONE', 'persistencebackup': 'NONE', 'lbmethod': 'ROUNDROBIN', 'pq': 'OFF', 'sc': 'OFF', 'clttimeout': '180', 'downstateflush': 'ENABLED', 'comment': 'Vserver created by ansible'}",
        "ModuleExecutor.calculate_configured_service_bindings()",
        "ModuleExecutor.calculate_configured_servicegroup_bindings()",
        "calculated configured servicegroup bindings [{'name': 'DEV-STEVE-management_vsrv', 'servicegroupname': 'DEV-STEVE-management_svcgrp', 'weight': '1'}]",
        "ModuleExecutor.calculate_configured_appfwpolicy_bindings()",
        "ModuleExecutor.update_or_create()",
        "ModuleExecutor.lbvserver_exists()",
        "get result {'http_response_data': {'url': 'https://xxx.yyy.zzz.aaa/nitro/v1/config/lbvserver/DEV-STEVE-management_vsrv', 'status': 200, 'date': 'Wed, 21 Apr 2021 20:17:13 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'vary': 'Accept-Encoding', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '2170', 'connection': 'close', 'content-type': 'application/json; charset=utf-8', 'cookies_string': '', 'cookies': {}, 'msg': 'OK (2170 bytes)'}, 'nitro_errorcode': 0, 'nitro_message': 'Done', 'nitro_severity': 'NONE', 'data': {'errorcode': 0, 'message': 'Done', 'severity': 'NONE', 'lbvserver': [{'name': 'DEV-STEVE-management_vsrv', 'insertvserveripport': 'OFF', 'value': 'Certkey not bound', 'ipv46': 'xxx.yyy.zzz.220', 'ippattern': '0.0.0.0', 'ipmask': '*', 'listenpolicy': 'NONE', 'ipmapping': '0.0.0.0', 'port': 443, 'range': '1', 'servicetype': 'SSL', 'type': 'ADDRESS', 'curstate': 'DOWN', 'effectivestate': 'DOWN', 'status': 3, 'lbrrreason': 8, 'cachetype': 'SERVER', 'authentication': 'OFF', 'authn401': 'OFF', 'dynamicweight': '0', 'priority': '0', 'clttimeout': '180', 'somethod': 'NONE', 'sopersistence': 'DISABLED', 'sopersistencetimeout': '2', 'healththreshold': '0', 'lbmethod': 'ROUNDROBIN', 'dataoffset': '0', 'health': '0', 'datalength': '0', 'ruletype': '0', 'm': 'IP', 'persistencetype': 'NONE', 'timeout': 2, 'persistmask': '255.255.255.255', 'v6persistmasklen': '128', 'persistencebackup': 'NONE', 'backuppersistencetimeout': 2, 'cacheable': 'NO', 'rtspnat': 'OFF', 'sessionless': 'DISABLED', 'trofspersistence': 'ENABLED', 'map': 'OFF', 'connfailover': 'DISABLED', 'redirectportrewrite': 'DISABLED', 'downstateflush': 'ENABLED', 'disableprimaryondown': 'DISABLED', 'gt2gb': 'DISABLED', 'consolidatedlconn': 'GLOBAL', 'consolidatedlconngbl': 'YES', 'thresholdvalue': 0, 'invoke': False, 'version': 0, 'totalservices': '0', 'activeservices': '0', 'statechangetimesec': 'Wed Apr 21 15:09:19 2021', 'statechangetimeseconds': '1619017759', 'statechangetimemsec': '709', 'tickssincelaststatechange': '1847384', 'hits': '0', 'pipolicyhits': '0', 'push': 'DISABLED', 'pushlabel': 'none', 'pushmulticlients': 'NO', 'comment': 'Vserver created by ansible', 'policysubtype': '0', 'l2conn': 'OFF', 'appflowlog': 'ENABLED', 'isgslb': False, 'icmpvsrresponse': 'PASSIVE', 'rhistate': 'PASSIVE', 'newservicerequestunit': 'PER_SECOND', 'vsvrbindsvcip': 'xxx.yyy.zzz.220', 'vsvrbindsvcport': 0, 'skippersistency': 'None', 'td': '0', 'minautoscalemembers': '0', 'maxautoscalemembers': '0', 'macmoderetainvlan': 'DISABLED', 'dns64': 'DISABLED', 'bypassaaaa': 'NO', 'processlocal': 'DISABLED', 'vsvrdynconnsothreshold': '0', 'retainconnectionsoncluster': 'NO', 'nodefaultbindings': 'NO'}]}}",
        "ModuleExecutor.lbvserver_identical()",
        "Attribute \"pq\" differs. Playbook parameter: (<class 'str'>) OFF. Retrieved NITRO object: (<class 'NoneType'>) None",
        "Attribute \"sc\" differs. Playbook parameter: (<class 'str'>) OFF. Retrieved NITRO object: (<class 'NoneType'>) None",
        "Existing lbvserver does not have identical values to configured. Will update.",
        "ModuleExecutor.update_lbvserver()",
        "request put data: {'lbvserver': {'name': 'DEV-STEVE-management_vsrv', 'ipv46': 'xxx.yyy.zzz.220', 'persistencetype': 'NONE', 'persistencebackup': 'NONE', 'lbmethod': 'ROUNDROBIN', 'pq': 'OFF', 'sc': 'OFF', 'clttimeout': '180', 'downstateflush': 'ENABLED', 'comment': 'Vserver created by ansible'}}",
        "result of put: {'http_response_data': {'url': 'https://xxx.yyy.zzz.aaa/nitro/v1/config/lbvserver', 'status': 200, 'date': 'Wed, 21 Apr 2021 20:17:13 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '57', 'connection': 'close', 'content-type': 'application/json; charset=utf-8', 'cookies_string': '', 'cookies': {}, 'msg': 'OK (57 bytes)'}, 'nitro_errorcode': 0, 'nitro_message': 'Done', 'nitro_severity': 'NONE', 'data': {'errorcode': 0, 'message': 'Done', 'severity': 'NONE'}}",
        "ModuleExecutor.sync_bindings()",
        "ModuleExecutor.sync_service_bindings()",
        "ModuleExecutor.get_existing_service_bindings()",
        "existing_service_bindings []",
        "configured_already_present []",
        "ModuleExecutor.sync_servicegroup_bindings()",
        "ModuleExecutor.get_existing_servicegroup_bindings()",
        "existing_servicegroup_bindings []",
        "configured_already_present []",
        "Configured binding does not already exist",
        "ModuleExecutor.add_servicegroup_binding()",
        "put data {'lbvserver_servicegroup_binding': {'name': 'DEV-STEVE-management_vsrv', 'servicegroupname': 'DEV-STEVE-management_svcgrp', 'weight': '1'}}",
        "result of put: {'http_response_data': {'url': 'https://xxx.yyy.zzz.aaa/nitro/v1/config/lbvserver_servicegroup_binding/DEV-STEVE-management_vsrv', 'status': 400, 'date': 'Wed, 21 Apr 2021 20:17:14 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '109', 'connection': 'close', 'content-type': 'application/json; charset=utf-8', 'msg': 'HTTP Error 400: Bad Request'}, 'nitro_errorcode': 1093, 'nitro_message': 'Argument pre-requisite missing [weight, serviceName]', 'nitro_severity': 'ERROR', 'data': {'errorcode': 1093, 'message': 'Argument pre-requisite missing [weight, serviceName]', 'severity': 'ERROR'}}"
    ],
    "msg": "nitro exception errorcode=1093, message=Argument pre-requisite missing [weight, serviceName], severity=ERROR"
}

**Comment by giorgos-nikolopoulos** [comment]
You need to omit the `weight` from the servicegroup binding.

When binding servicegroups from the nscli setting a weight is not supported.

NITRO may allow it but the configuration engine throws an error.

**Comment by semora81** [comment]
thanks

**Comment by vadharm** [comment]
Resolved
