### ISSUE TITLE
LDAP Action keeps reporting "Changed" due to password.

### ISSUE THREAD

**Issue by mkallesoe** [citrix/citrix-adc-ansible-modules#195]
after each run, ansible reports "chagned"

-snip:
"Attribute \"ldapbinddnpassword\" differs. Playbook parameter: (<class 'str'>) Simcorp1. Retrieved NITRO object: (<class 'str'>) 08e33273648f26f40127a1effbf06900b0ec2871e1fef969554e3b2fbdaa5dd7",
-/snip

Which is understandable, but should be expected, and i suppose handled in the module.

**Comment by giorgos-nikolopoulos** [comment]
Which module is the one you are referring to?

**Comment by mkallesoe** [comment]
The ansible module - i am trying to create an LDAP aciton, with 
  authenticationldapaction:
    lifecycle: object
    endpoint: authenticationldapaction
    primary_id_attribute: name
    resource_missing_errorcode: 538
    delete_id_attributes:
      - name

**Comment by giorgos-nikolopoulos** [comment]
Seems you are using `citrix_adc_nitro_resource` with a custom workflow dictionary.

This module's logic is to always compare the given attributes with what is retrieved from the ADC.

The solution would be to add a new entry to the workflow dictionary to ignore the comparison of certain attributes when assessing  the equality of the local and remote state.

We will keep this in mind for the next iteration of bugfixes we do for the modules.

**Comment by mkallesoe** [comment]
Arh, yes, i am using the citrix_adc_nitro_resource module.

And you suggestions seems very legit, i am intrigued
