### ISSUE TITLE
citrix_adc_cs_vserver

### ISSUE THREAD

**Issue by rajspeed1** [citrix/citrix-adc-ansible-modules#208]
Can someone help to update

param - **validate_certs** is not behaving as exprected.

request is failing ,
Error
 'msg': 'Request failed: <urlopen error _ssl.c:880: The handshake operation timed out>'}, 'nitro_errorcode': None, 'nitro_message': None, 'nitro_severity': None}"

**Comment by giorgos-nikolopoulos** [comment]
Please share the playbook you are seeing this error with.

Right now we don't have enough information to troubleshoot this.

**Comment by sumanth-lingappa** [comment]
@rajspeed1: closing this as we do not have enough data to work on your issue.

Please reopen the issue with the right playbook you are trying.
