### ISSUE TITLE
nitrosdk-python is not existing on public pypi anymore

### ISSUE THREAD

**Issue by bts-dido** [citrix/citrix-adc-ansible-modules#222]
Already created [issue on pypi support](https://github.com/pypa/pypi-support/issues/1866), but no progress, so creating issue here to ask.

We're using netscaler ansible module and, we were downloading required nitrosdk-python library from public pypi server until 2022/4/20. But now we're not able to download it.  Who is the maintainer of the nitrosdk-python and can we ask why it's deleted on public pypi repo?

Without library, we're seeing error like below. Ansible version: `2.9.26`
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not load nitro python sdk"}
```

I see this github repository still depends on nitrosdk-python.
https://github.com/citrix/citrix-adc-ansible-modules/blob/241b8ae05a57171050cf710de4774409a6ca29ee/ansible-collections/adc/plugins/modules/citrix_adc_server.py#L286-L288

**Comment by vadharm** [comment]
@bts-dido We will address this, could you drop us email at mayur.vadhar1@citrix.com to take this further. @giorgos-nikolopoulos Please look into this.

**Comment by bts-dido** [comment]
@vadharm 

> @bts-dido We will address this, could you drop us email at [mayur.vadhar1@citrix.com](mailto:mayur.vadhar1@citrix.com) to take this further. @giorgos-nikolopoulos Please look into this.

Thanks for the response! Mail sent.

**Comment by giorgos-nikolopoulos** [comment]
@bts-dido We are not the maintainers of the pypi package.

My suggestion is to use the nitro python sdk present in this repository which can be found [here](https://github.com/citrix/citrix-adc-ansible-modules/blob/master/deps/nitro-python-1.0_kamet.tar.gz)

**Comment by sumanth-lingappa** [comment]
@bts-dido : did you try using the nitro python SDK from the repository @giorgos-nikolopoulos mentioned? 
Please update us if it worked for you.

**Comment by sumanth-lingappa** [comment]
@bts-dido : closing this as @giorgos-nikolopoulos solution should work. 
Please re-open if you face any issue.
Thank you.
