### ISSUE TITLE
52 vulnaribilities according trivy 

### ISSUE THREAD

**Issue by pbptaker** [citrix/citrix-adc-ansible-modules#227]
Dear Developers

According our trivy scanner there are 52 vulnerabilities, wheras most of them are fixable.

![image](https://user-images.githubusercontent.com/35006190/172629805-832fbc16-5174-4ec3-8e7a-c665c76d052f.png)

Can you please update those packages? How should I upload the detailed cve-report?

Thanky you, pbptaker

**Comment by vadharm** [comment]
Hi @pbptaker , Appreciate you bringing this up. Please drop email and attach the report to mayur.vadhar1@citrix.com and Giorgos.Nikolopoulos@citrix.com , and we take it from there.
Best,
Mayur

**Comment by pbptaker** [comment]
sent you the info using our filetransfer service (don't want to send cve lists unencypted by email). thank you

**Comment by pbptaker** [comment]
There was a misunderstanding. The image generating this vulnerabilities list is not coming from citrix, it is coming from https://github.com/virtualdesktopdevops/citrix-adc-ansible-modules-docker instead. So there the image has to be updated in order to fix the vulnerabilities.
