### ISSUE TITLE
404 on creating sericegroup or lb vserver

### ISSUE THREAD

**Issue by pbptaker** [citrix/citrix-adc-ansible-modules#232]
Dear developers

Even when I use the servicegroup sample from the samples folder:

---
- hosts: citrix_adc

  vars:
    max_clients: 5
  collections:
    - citrix.adc

  remote_user: root
  gather_facts: False

  tasks:
    - name: Set server 1
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present
        name: server-1
        ipaddress: 10.11.11.12

    - name: Set server 2
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present
        name: server-2
        ipaddress: 10.11.11.13

    - name: Set service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicegroupname: service-group-1
        servicetype: HTTP
        clttimeout: 300
        servicemembers:
          mode: exact
          attributes:
            - servername: server-1
              port: 8080
              weight: 50

then it creates me both servers, but not the servicegroup similar to issue #202

PLAY [citrix_adc] **************************************************************

TASK [Set server 1] ************************************************************
ok: [ejpdvt6820 -> localhost]

TASK [Set server 2] ************************************************************
ok: adc1 -> localhost]

TASK [Set service group] *******************************************************
fatal: [adc1 -> localhost]: FAILED! => {"changed": false, "loglines": ["ModuleExecutor.calculate_configured_servicegroup()", "calculated configured servicegroup {'servicegroupname': 'service-group-1', 'servicetype': 'HTTP', 'clttimeout': 300}", "ModuleExecutor.calculate_configured_servicemembers()", "calculated configured service members [{'servicegroupname': 'service-group-1', 'port': 8080, 'weight': '50', 'servername': 'server-1'}]", "ModuleExecutor.calculate_configured_monitor_bindings()", "ModuleExecutor.update_or_create()", "ModuleExecutor.servicegroup_exists()", "get result {'http_response_body': '', 'http_response_data': {'url': 'https://10.199.192.40:443/nitro/v1/config/servicegroup/service-group-1', 'status': 404, 'date': 'Thu, 18 Aug 2022 11:52:28 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'vary': 'Accept-Encoding', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '108', 'content-type': 'application/json; charset=utf-8', 'connection': 'close', 'strict-transport-security': 'max-age=0', 'msg': 'HTTP Error 404: Not Found', 'body': b'{ \"errorcode\": 258, \"message\": \"No such resource [serviceGroupName, service-group-1]\", \"severity\": \"ERROR\" }'}, 'nitro_errorcode': None, 'nitro_message': None, 'nitro_severity': None}"], "msg": "nitro exception errorcode=None, message=None, severity=None"}

PLAY RECAP *********************************************************************
adc1               : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

I'm getting the same 404 when creating a lb vserver using a correkt yaml. 

What is wrong in my environment?

thank you

pbptaker

**Comment by sumanth-lingappa** [comment]
@pbptaker looks like it's ansible version mismatching.

Please install the relevant ansible (https://github.com/citrix/citrix-adc-ansible-modules#pre-requisites)

As of today, citrix_adc_* modules are tested for ansible version `2.12` or below.

Let here know your findings.

**Comment by pbptaker** [comment]
Thanks sumanth-lingappa.
Indeed I'm using 2.13.2. So a'm changing to a version <= 2.12 and let you know

**Comment by pbptaker** [comment]
Correct. It works using ansible 2.12. thanks
