### ISSUE TITLE
[BUG] adc/plugins/module_utils/citrix_adc.py - fails to populate nitro_* parameters

### ISSUE THREAD

**Issue by HS1542** [citrix/citrix-adc-ansible-modules#242]
Tested towards a Netscaler 13.1 33.49

While trying to run for instance citrix_adc_nsip to add an IP address it will fail due to the part where nsip_exists() will check if the IP address is already present. The errorcode 258 is included in the API response, but not placed correctly in the nitro_errorcode by module_utils/citrix_adc.py:

This seems to be a duplicate of the unassigned bug issue #232

"calculated configured nsip {'ipaddress': '192.168.128.31', 'netmask': '255.255.255.0', 'type': 'SNIP', 'arp': 'ENABLED', 'icmp': 'ENABLED', 'telnet': 'DISABLED', 'ftp': 'DISABLED', 'gui': 'DISABLED', 'ssh': 'DISABLED', 'snmp': 'DISABLED', 'mgmtaccess': 'DISABLED'}",
        "ModuleExecutor.update_or_create()",
        "ModuleExecutor.nsip_exists()",
        "get result {'http_response_body': '', 'http_response_data': {'url': 'https://192.168.128.21/nitro/v1/config/nsip?args=ipaddress:192.168.128.31', 'status': 404, 'date': 'Thu, 17 Nov 2022 11:58:46 GMT', 'server': 'Apache', 'x-frame-options': 'SAMEORIGIN', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'pragma': 'no-cache', 'vary': 'Accept-Encoding', 'feature-policy': \"camera 'none'; microphone 'none'; geolocation 'none'\", 'referrer-policy': 'no-referrer', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-length': '103', 'content-type': 'application/json; charset=utf-8', 'connection': 'close', 'msg': 'HTTP Error 404: Not Found', 'body': b'{ **\"errorcode\": 258,** \"message\": \"No such resource [(IPAddress, , 192.168.128.31]\", \"severity\": \"ERROR\" }'}, 'nitro_errorcode': None, 'nitro_message': None, 'nitro_severity': None}"
    ],
    "msg": "**nitro exception errorcode=None**, message=None, severity=None"

**Comment by sumanth-lingappa** [comment]
@HS1542 looks like ansible version is mismatching.

Please install the relevant ansible (https://github.com/citrix/citrix-adc-ansible-modules#pre-requisites)

As of today, citrix_adc_* modules are tested for ansible version 2.12 or below.

Let here know your findings.

**Comment by HS1542** [comment]
Ansible 2.9.6 installed from the universe repository of Ubuntu 20.04, so it should be within the pre-requisites ?

**Comment by sumanth-lingappa** [comment]
Yes, @HS1542. We have not tested our modules for ansible versions beyond what is mentioned in prerequisites.

Installing ansible beyond the version mentioned in the prerequisites may break our modules.

We are planning to update our modules to make it compatible to the latest version of ansible possible. 

However, PRs are welcome.

Please let here know if this solves your issue for now.

**Comment by HS1542** [comment]
Hello,

I do not follow you here, 2._9_.6 is less than 2.12, so in regards to the documentation, the version of ansible should be no problem here? Perhaps there has been some changes in the Nitro API on v13.1 or some other part? It should be quite easy to reproduce.
However, I see that I have been using pip packages, so the version is as you correct stated updated: ansible-core 2.13.5 and ansible 6.5.0.

This solves my issue for now, thank you!

However, could you share some thoughts on how Citrix will proceed with the support of ansible modules? There seems to be much more development and resources going into a full Terraform provider, which as far as I can see works as expected in most cases. What about Ansible? Can we expect some further development on the ansible modules, or should we focus on plain nitro requests?

**Comment by sumanth-lingappa** [comment]
That's great to know @HS1542 

We will address your last paragraph question separately. I am closing this since we got the resolution.

Please re-open this issue or open another issue if you find anything else.

Please reach out to us at appmodernization@citrix.com if any of your required modules is not present in ansible. We can plan and prioritise them to support.

Please help us to understand your use-case.
