### ISSUE TITLE
Passing passwords to module securely?

### ISSUE THREAD

**Issue by felipe1982** [citrix/citrix-adc-ansible-modules#94]
What is the recommended way to pass password to the citrix_adc_* modules? We would like passwords to NOT appear in the console, and NOT appear in any log files. `no_log: True` is not an option, because it hides useful error messages when things go wrong.

**Comment by giorgos-nikolopoulos** [comment]
For all the modules the parameters `nitro_user` and `nitro_pass` have the `no_log` option set to true.
Also for the parameter `passplain` for citrix_adc_ssl_cerkey` has the same option set to true.

For these attributes no printing of actual values will happen when running a playbook.

If you would like to have some other attribute selectively turned off for logging, I am not aware of any other way to implement it than altering the module code for this option.

As you said specifying `no_log: true` in the task will hide all output for this one task.

Which attributes in particular are you interested in setting the `no_log` option?
