### ISSUE TITLE
Easier install method

### ISSUE THREAD

**Issue by brilong** [citrix/citrix-adc-ansible-modules#96]
My team uses these modules to manage our Netscaler/ADC, but keeping these modules up to date using Ansible itself is difficult.  First of all, these modules overwrite files owned by the ansible RPM provided by upstream.  Second, I cannot simply "pip install citrix-adc-ansible-modules" and pull down all dependencies, etc. 
My ansible masters should be able to easily install and update these modules as I deem necessary by using the "pip" module or some other package management system instead of calling a install.py script.  Is there any work being done to make this easier for unattended installs?  Thanks.

**Comment by giorgos-nikolopoulos** [comment]
The most appropriate solution for this would be to have our repository up to date with the ansible official release.

We do syncs periodically but unfortunately, depending on the work load, there are periods that this repository is ahead of the ansible repository.

The `install.py` script was, at the time of creation, the most time efficient solution to this out of sync gap.

Right now we are in the process of updating all modules to the latest stable NITRO API version and adding some new modules.

After that task is complete we will address this issue.

I don't think we will be able to provide .rpm and .deb packages but pip packages and possibly some other means of python package distribution will be implemented.

Thank you for bringing this issue to our attention.

**Comment by brilong** [comment]
Thank you for the update.  Making these modules available via pip would be sufficient for my needs and I appreciate your efforts in this regard.  I would also like to understand exactly which "latest stable NITRO API" you mean and which level of code is required.  We're still running the 11.1 branch on our devices and I will be interested to hear if 12.1 is required for certain functionality.  Thanks again!

**Comment by giorgos-nikolopoulos** [comment]
Latest stable at this point in time means the 13.0 41.20 build of ADC.

From my experience so far the NITRO API will add attributes to existing resources and will try not to break compatibility with older versions. This is especially true of long standing configuration items, such as services, vservers etc.

The modules as well try to maintain compatibility by not including in the request fields that are not set by the user. So if you have an older version of the ADC, not including the fields that are not available is enough for the module to work correctly with the particular version.

For changes across NITRO versions [this document](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/nitro-changes-across-releases/) should be useful.

**Comment by brilong** [comment]
I'm also struggling to understand when I should use the Ansible built-in netscaler_foo modules vs. overriding them with your newer citrix_foo modules.  My team has been using Ansible 2.7.x plus the citrix_ modules from this site because the built-in modules had deficiencies.  As we migrate to Ansible 2.8 and beyond, the built-in modules are now named netscaler_ and your modules install along-side them cleanly without overwriting files owned by the Ansible RPM.  Is there any reason I should move back to the Ansible-provided netscaler_ modules or do you recommend staying on your citrix_ modules since we already have working roles?  Thanks for any insight you can provide.

**Comment by giorgos-nikolopoulos** [comment]
The modules in this repository are the most up to date.
So I would recommend using them over the ones available in ansible repository.
