### ISSUE TITLE
ansible module for adm service

### ISSUE THREAD

**Issue by hardjopranoto** [citrix/citrix-adc-ansible-modules#99]
do you have a module that communicate with ADM service instead of ADM on-prem?

i believe most of the API calls are very similar.

ADM service uses https://<ip address>/nitro/v1/ URL

ADM service is also expecting parameter 'isCloud: true' in the header.

ADM service also uses ClientID and Secret (which is the API key) instead of the standard username and password. 

daniel

**Comment by giorgos-nikolopoulos** [comment]
It is possible to modify the modules to work with adm service.

We will schedule the implementation of this feature for some time in the future.

@hardjopranoto thanks for bringing this to our attention.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #180
